//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audits
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Audits()
        {
            this.RegularAudit = new HashSet<RegularAudits>();
            this.IRMERAudit1 = new HashSet<IRMERAudits>();
        }
    
        public int Id { get; set; }
        public short TypeID { get; set; }
        public short StatusID { get; set; }
        public short MethodID { get; set; }
        public short ActionPlanID { get; set; }
        public short OutcomeID { get; set; }
        public short PresentationID { get; set; }
        public short StandardsID { get; set; }
        public short AuthorID { get; set; }
        public short ManagerID { get; set; }
        public string Reference { get; set; }
        public short OwnerID { get; set; }
        public short RoleID { get; set; }
        public string AuditID { get; set; }
        public string IRMERAuditID { get; set; }
    
        public virtual AuditTypes AuditTypes { get; set; }
        public virtual AuditPresentations AuditPresentation { get; set; }
        public virtual AuditActionPlans AuditActionPlan { get; set; }
        public virtual AuditSOPs AuditSOP { get; set; }
        public virtual AuditStandards AuditStandard { get; set; }
        public virtual AuditMethods AuditMethod { get; set; }
        public virtual AuditOutcomes AuditOutcome { get; set; }
        public virtual AuditStatus AuditStatu { get; set; }
        public virtual Staff Author { get; set; }
        public virtual Staff Manager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RegularAudits> RegularAudit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IRMERAudits> IRMERAudit1 { get; set; }
    }
}
