//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS6
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTypes
    {
        public int Id { get; set; }
        public bool Type { get; set; }
    
        public virtual Audits Audit { get; set; }
    }
}
