//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS6
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Audits> Audits { get; set; }
        public virtual DbSet<AuditStatus> AuditStatus { get; set; }
        public virtual DbSet<AuditTypes> AuditTypes { get; set; }
        public virtual DbSet<AuditPresentations> AuditPresentations { get; set; }
        public virtual DbSet<Staff> Staffs { get; set; }
        public virtual DbSet<AuditActionPlans> AuditActionPlans { get; set; }
        public virtual DbSet<AuditMethods> AuditMethods { get; set; }
        public virtual DbSet<AuditOutcomes> AuditOutcomes { get; set; }
        public virtual DbSet<AuditFrequencies> AuditFrequencies { get; set; }
        public virtual DbSet<AuditStandards> AuditStandards { get; set; }
        public virtual DbSet<IRMERAudits> IRMERAudits { get; set; }
        public virtual DbSet<RegularAudits> RegularAudits { get; set; }
        public virtual DbSet<AuditSOPs> AuditSOPs { get; set; }
    }
}
