//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS6
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int Id { get; set; }
        public string FIrstName { get; set; }
        public string LastName { get; set; }
        public string EMail { get; set; }
    
        public virtual Audits Author { get; set; }
        public virtual Audits Manager { get; set; }
        public virtual AuditPresentations AuditPresentation { get; set; }
    }
}
