//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QMS5
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ReviewDate { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<System.DateTime> CheckoutDate { get; set; }
        public int TypeID { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public int AuthorID { get; set; }
        public Nullable<int> ManagerID { get; set; }
    
        public virtual DocumentAction DocumentAction { get; set; }
        public virtual DocumentStatu DocumentStatu { get; set; }
        public virtual DocumentType DocumentType { get; set; }
        public virtual Staff Author { get; set; }
        public virtual Staff Manager { get; set; }
    }
}
